/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { extend, useFrame, useLoader } from "@react-three/fiber"
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import * as Nodes from "three/examples/jsm/nodes/Nodes.js"
import {BuildingMat} from '../Building.mat'

extend(Nodes)
function randomColor() {
  var color = "#"
  var randomHex = "123456ABCDEF"
  for (let i = 0; i < 6; i++) {
    color += randomHex[Math.floor(Math.random() * 16)]
  }

  return color
}

export default function Model({colors,...props}) {
  
  
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Buildings/Castle.glb')
    
  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM_Castle.geometry} castShadow transparent
        receiveShadow >
        {!props.children?
          <BuildingMat></BuildingMat>
        : props.children
        }
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Buildings/Castle.glb')
