/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { BuildingMat } from './Building.mat'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Models/HWeapons/BallistaLl2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <skinnedMesh
        geometry={nodes.SK_Ballista_lvl2.geometry}
        skeleton={nodes.SK_Ballista_lvl2.skeleton}
        castShadow receiveShadow transparent>
        <BuildingMat></BuildingMat>

        <primitive object={nodes.BONE_BASE} />
      </skinnedMesh>
    </group>
  )
}

useGLTF.preload('/Models/HWeapons/BallistaLl2.glb')