/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Castillo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1, 4.9, -2]} rotation={[-2.72, 0.3, 2.09]} scale={2.5} />
      <group position={[1.81, 11.14, 6.46]} />
      <group position={[0.11, 5.35, -0.31]} />
      <group position={[-0.11, 2.67, -0.09]} />
      <group position={[10.7, 0.3, 26]}>
        <primitive object={nodes.Bone_Pole} />
        <skinnedMesh
          geometry={nodes.SK_Banner_A.geometry}
          material={nodes.SK_Banner_A.material}
          skeleton={nodes.SK_Banner_A.skeleton}
        />
      </group>
      <group position={[20.2, 0.3, 25.6]}>
        <primitive object={nodes.Bone_Pole_1} />
        <skinnedMesh
          geometry={nodes.SK_Banner_A001.geometry}
          material={nodes.SK_Banner_A001.material}
          skeleton={nodes.SK_Banner_A001.skeleton}
        />
      </group>
      <group position={[3.17, 5.34, 11.87]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.7}>
        <primitive object={nodes.BONE_BASE} />
        <skinnedMesh
          geometry={nodes.SK_Ballista_lvl3.geometry}
          material={nodes.SK_Ballista_lvl3.material}
          skeleton={nodes.SK_Ballista_lvl3.skeleton}
        />
      </group>
      <group position={[27.37, 5.34, 11.97]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.7}>
        <primitive object={nodes.BONE_BASE_1} />
        <skinnedMesh
          geometry={nodes.SK_Ballista_lvl3001.geometry}
          material={nodes.SK_Ballista_lvl3001.material}
          skeleton={nodes.SK_Ballista_lvl3001.skeleton}
        />
      </group>
      <group position={[27.37, 5.34, 23.87]} scale={0.7}>
        <primitive object={nodes.BONE_BASE_2} />
        <skinnedMesh
          geometry={nodes.SK_Ballista_lvl3002.geometry}
          material={nodes.SK_Ballista_lvl3002.material}
          skeleton={nodes.SK_Ballista_lvl3002.skeleton}
        />
      </group>
      <group position={[3.57, 5.34, 23.77]} scale={0.7}>
        <primitive object={nodes.BONE_BASE_3} />
        <skinnedMesh
          geometry={nodes.SK_Ballista_lvl3003.geometry}
          material={nodes.SK_Ballista_lvl3003.material}
          skeleton={nodes.SK_Ballista_lvl3003.skeleton}
        />
      </group>
      <group position={[8.5, 4.2, 24]}>
        <primitive object={nodes.Bip001} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman.geometry}
          material={nodes.SK_Crossbowman.material}
          skeleton={nodes.SK_Crossbowman.skeleton}
        />
      </group>
      <group position={[22.3, 4.2, 24]}>
        <primitive object={nodes.Bip001_1} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman001.geometry}
          material={nodes.SK_Crossbowman001.material}
          skeleton={nodes.SK_Crossbowman001.skeleton}
        />
      </group>
      <group position={[21.3, 4.2, 11.8]} rotation={[Math.PI, 0, Math.PI]}>
        <primitive object={nodes.Bip001_2} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman002.geometry}
          material={nodes.SK_Crossbowman002.material}
          skeleton={nodes.SK_Crossbowman002.skeleton}
        />
      </group>
      <group position={[27.8, 4.2, 19.1]} rotation={[0, Math.PI / 2, 0]}>
        <primitive object={nodes.Bip001_3} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman003.geometry}
          material={nodes.SK_Crossbowman003.material}
          skeleton={nodes.SK_Crossbowman003.skeleton}
        />
      </group>
      <group position={[9.5, 4.2, 11.8]} rotation={[Math.PI, 0, Math.PI]}>
        <primitive object={nodes.Bip001_4} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman004.geometry}
          material={nodes.SK_Crossbowman004.material}
          skeleton={nodes.SK_Crossbowman004.skeleton}
        />
      </group>
      <group position={[3.2, 4.2, 17.2]} rotation={[0, -Math.PI / 2, 0]}>
        <primitive object={nodes.Bip001_5} />
        <skinnedMesh
          geometry={nodes.SK_Crossbowman005.geometry}
          material={nodes.SK_Crossbowman005.material}
          skeleton={nodes.SK_Crossbowman005.skeleton}
        />
      </group>
      <group position={[12.7, 0.2, 25.9]}>
        <primitive object={nodes.Bip001_6} />
        <skinnedMesh
          geometry={nodes.SK_Spearman.geometry}
          material={nodes.SK_Spearman.material}
          skeleton={nodes.SK_Spearman.skeleton}
        />
      </group>
      <group position={[18.2, 0.2, 25.9]}>
        <primitive object={nodes.Bip001_7} />
        <skinnedMesh
          geometry={nodes.SK_Spearman001.geometry}
          material={nodes.SK_Spearman001.material}
          skeleton={nodes.SK_Spearman001.skeleton}
        />
      </group>
      <mesh
        geometry={nodes.Wall_B_gate_Wall_B_gate_door_83_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_gate_Wall_B_gate_door_83_StaticMeshComponent0.material}
        position={[15.5, 0.2, 24.8]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.08, 1, 1]}
      />
      <mesh
        geometry={nodes.Castle2_StaticMeshComponent0.geometry}
        material={nodes.Castle2_StaticMeshComponent0.material}
        position={[15.6, 0.15, 18.71]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall2_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall2_StaticMeshComponent0.material}
        position={[18.74, 0.13, 11.9]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall3_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall3_StaticMeshComponent0.material}
        position={[12.94, 0.13, 11.9]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall4_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall4_StaticMeshComponent0.material}
        position={[6.94, 0.13, 11.9]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall5_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall5_StaticMeshComponent0.material}
        position={[3.04, 0.13, 16.2]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall6_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall6_StaticMeshComponent0.material}
        position={[3.04, 0.13, 22.2]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall7_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall7_StaticMeshComponent0.material}
        position={[7.54, 0.13, 24.2]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall8_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall8_StaticMeshComponent0.material}
        position={[23.04, 0.13, 11.9]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall9_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall9_StaticMeshComponent0.material}
        position={[23.14, 0.13, 24.2]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1.01]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall10_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall10_StaticMeshComponent0.material}
        position={[27.84, 0.13, 16.2]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall11_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall11_StaticMeshComponent0.material}
        position={[27.84, 0.13, 19.5]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall12_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall12_StaticMeshComponent0.material}
        position={[21.54, 0.13, 24.2]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1.01]}
      />
      <mesh
        geometry={nodes.Wall_B_wall_Wall_B_wall13_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_wall_Wall_B_wall13_StaticMeshComponent0.material}
        position={[9.54, 0.13, 24.2]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Tower_C2_StaticMeshComponent0.geometry}
        material={nodes.Tower_C2_StaticMeshComponent0.material}
        position={[8.3, 2.29, 17.85]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Tower_C3_StaticMeshComponent0.geometry}
        material={nodes.Tower_C3_StaticMeshComponent0.material}
        position={[23.2, 1.99, 17.35]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall_B_corner_Wall_B_corner2_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_corner_Wall_B_corner2_StaticMeshComponent0.material}
        position={[3.2, -0.12, 12.02]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1.15, 1]}
      />
      <mesh
        geometry={nodes.Wall_B_corner_Wall_B_corner3_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_corner_Wall_B_corner3_StaticMeshComponent0.material}
        position={[27.4, -0.12, 11.92]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1.15, 1]}
      />
      <mesh
        geometry={nodes.Wall_B_corner_Wall_B_corner4_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_corner_Wall_B_corner4_StaticMeshComponent0.material}
        position={[27.4, -0.12, 23.72]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1.15, 1]}
      />
      <mesh
        geometry={nodes.Wall_B_corner_Wall_B_corner5_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_corner_Wall_B_corner5_StaticMeshComponent0.material}
        position={[3.4, -0.12, 23.92]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1.16, 1]}
      />
      <mesh
        geometry={nodes.Wall_B_gate_Wall_B_gate2_StaticMeshComponent0.geometry}
        material={nodes.Wall_B_gate_Wall_B_gate2_StaticMeshComponent0.material}
        position={[15.5, 0.2, 24.5]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/Castillo.glb')
