/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Models/Decorations/Tree.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Tree.geometry} material={nodes.Tree.material} />
    </group>
  )
}

useGLTF.preload('/Models/Decorations/Tree.glb')
