/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/grass_05_brush_05.glb')
  return (
    <group ref={group} {...props} dispose={null}  >
      <mesh geometry={nodes.grass_05_brush_05.geometry} material={materials.Grass_05_Brush_05_Mat} />
    </group>
  )
}

useGLTF.preload('/models/grass_05_brush_05.glb')
