/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF,useMatcapTexture } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const [matcapArrowMove] = useMatcapTexture('54C104_BBFA0F_97EF04_7AE104' )
  const { nodes } = useGLTF('/models/ArrowMove.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.ArrowMove.geometry} > 
            <meshMatcapMaterial attach="material"  matcap={matcapArrowMove} />
      </mesh>
     
    </group>
  )
}

useGLTF.preload('/models/ArrowMove.glb')
