/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({berry = 0xFFFF00, wood = 0x60200F, leaf = 0x38610B, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/BushDec-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 180 * 90, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Sphere004_cherry_0_1.geometry}>
          <meshStandardMaterial color={berry}/>
          </mesh>
        <mesh geometry={nodes.Sphere004_cherry_0_2.geometry}>
          <meshStandardMaterial color={wood}/>
          </mesh>
        <mesh geometry={nodes.Sphere004_cherry_0_3.geometry}>
          <meshStandardMaterial color={leaf}/>
          </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('models/BushDec-transformed.glb')
