/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({color1=0x35652B, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Bush1-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.bush001.geometry}
        position={[2.77, 0.12, -3.47]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.77}
      >
      <meshStandardMaterial color={color1}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('models/Bush1-transformed.glb')
