/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/FarIsland.glb')
  return (
    <group rotation = {[0,Math.PI/180*-90,0]} position = {[15,-43,150]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM_FloatingIsland_S2_23_StaticMeshComponent0.geometry}>
	      <meshStandardMaterial color = {0xEcba00}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/FarIsland.glb')
