/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { extend, useFrame, useLoader } from "@react-three/fiber"
import * as THREE from 'three'


export default function Model({color='/Textures/FlowerOrange.webp', ...props }) {
  const group = useRef()
  const flower = useLoader(THREE.TextureLoader, color)

  const { nodes, materials } = useGLTF('/models/Floresitas2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.FlowerA_02010.geometry}
        rotation={[0.19, 0.98, -0.28]} transparent castShadow ReceiveShadow
      >
      <meshStandardMaterial map = {flower}>
      </meshStandardMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Floresitas2.glb')
