/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/fountain-transformed-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} scale={[6.95, 1, 6.95]} />
      <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} position={[0, 1.64, 0]} />
      <mesh geometry={nodes.Mesh_2.geometry} material={nodes.Mesh_2.material} />
    </group>
  )
}

useGLTF.preload('/models/fountain-transformed-transformed.glb')
