/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({color=0x25AA25, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Grass1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.grass001.geometry}
        position={[1.41, 0.03, -4.33]}
        scale={1.96}
      >
        <meshStandardMaterial  color={color}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Grass1.glb')
