/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF,useAnimations } from '@react-three/drei'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/AnimCavStaff-transformed.glb')
  const { ref, actions, names } = useAnimations(animations,group)

  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[0]].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names[index]].fadeOut(0.5)
  }, [actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <skinnedMesh
        geometry={nodes.SK_Mounted_Priest.geometry}
        material={materials.M_Units_Parent}
        skeleton={nodes.SK_Mounted_Priest.skeleton}>
        <primitive object={nodes.Bip001} />
      </skinnedMesh>
    </group>
  )
}

useGLTF.preload('/models/AnimCavStaff-transformed.glb')
