/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Map-v0.1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.SM_FloatingIsland_S_2_StaticMeshComponent0.geometry}
        material={materials.BasicAsset03}
        position={[-69.2, 0.2, -85]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[31.5, 31.5, 59]}
      />
    </group>
  )
}

useGLTF.preload('/Map-v0.1-transformed.glb')
