/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/mWater.glb')
  return (
    <group scale = {[480,1,422]} position = {[133,-7,1]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}>
      <meshStandardMaterial color = {0x2A74E7}></meshStandardMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/mWater.glb')