/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({color=0xa0a0a0, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/RockGrassBig-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.rock.geometry}>
        <meshStandardMaterial color={color}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('models/RockGrassBig-transformed.glb')
