/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Sample_Map_Reference.glb')
  return (
    <group ref={group} {...props} position={[100,0,70]} scale={} dispose={null}>
      <group position={[1, 7.3, -2]} rotation={[-2.72, 0.3, 2.09]} scale={2.5}>
        <directionalLight intensity={4} decay={2} rotation={[0, -1.57, 0]} />
      </group>
      <group position={[0.21, 5.05, -0.31]} />
      <group position={[-0.11, 2.67, -0.09]} />
      <mesh
        geometry={nodes.Library_26_StaticMeshComponent0.geometry}
        material={nodes.Library_26_StaticMeshComponent0.material}
        position={[52, 0.2, -1.3]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library2_StaticMeshComponent0.geometry}
        material={nodes.Library2_StaticMeshComponent0.material}
        position={[52, 0.2, -8.5]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library3_StaticMeshComponent0.geometry}
        material={nodes.Library3_StaticMeshComponent0.material}
        position={[52, 0.2, 13.2]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library4_StaticMeshComponent0.geometry}
        material={nodes.Library4_StaticMeshComponent0.material}
        position={[52, 0.2, 6]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library5_StaticMeshComponent0.geometry}
        material={nodes.Library5_StaticMeshComponent0.material}
        position={[52, 0.2, 27.9]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library6_StaticMeshComponent0.geometry}
        material={nodes.Library6_StaticMeshComponent0.material}
        position={[52, 0.2, 20.7]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library7_StaticMeshComponent0.geometry}
        material={nodes.Library7_StaticMeshComponent0.material}
        position={[52, 0.2, 42.4]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library8_StaticMeshComponent0.geometry}
        material={nodes.Library8_StaticMeshComponent0.material}
        position={[52, 0.2, 35.2]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library9_StaticMeshComponent0.geometry}
        material={nodes.Library9_StaticMeshComponent0.material}
        position={[52, 0.2, -60.1]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library10_StaticMeshComponent0.geometry}
        material={nodes.Library10_StaticMeshComponent0.material}
        position={[52, 0.2, -67.3]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library11_StaticMeshComponent0.geometry}
        material={nodes.Library11_StaticMeshComponent0.material}
        position={[52, 0.2, -45.6]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library12_StaticMeshComponent0.geometry}
        material={nodes.Library12_StaticMeshComponent0.material}
        position={[52, 0.2, -52.8]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library13_StaticMeshComponent0.geometry}
        material={nodes.Library13_StaticMeshComponent0.material}
        position={[52, 0.2, -30.9]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library14_StaticMeshComponent0.geometry}
        material={nodes.Library14_StaticMeshComponent0.material}
        position={[52, 0.2, -38.1]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library15_StaticMeshComponent0.geometry}
        material={nodes.Library15_StaticMeshComponent0.material}
        position={[52, 0.2, -16.4]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library16_StaticMeshComponent0.geometry}
        material={nodes.Library16_StaticMeshComponent0.material}
        position={[52, 0.2, -23.6]}
        rotation={[Math.PI, 1.57, -Math.PI]}
      />
      <mesh
        geometry={nodes.Library17_StaticMeshComponent0.geometry}
        material={nodes.Library17_StaticMeshComponent0.material}
        position={[-15.1, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library18_StaticMeshComponent0.geometry}
        material={nodes.Library18_StaticMeshComponent0.material}
        position={[-7.9, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library19_StaticMeshComponent0.geometry}
        material={nodes.Library19_StaticMeshComponent0.material}
        position={[-29.6, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library20_StaticMeshComponent0.geometry}
        material={nodes.Library20_StaticMeshComponent0.material}
        position={[-22.4, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library21_StaticMeshComponent0.geometry}
        material={nodes.Library21_StaticMeshComponent0.material}
        position={[-44.3, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library22_StaticMeshComponent0.geometry}
        material={nodes.Library22_StaticMeshComponent0.material}
        position={[-37.1, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library23_StaticMeshComponent0.geometry}
        material={nodes.Library23_StaticMeshComponent0.material}
        position={[-58.8, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library24_StaticMeshComponent0.geometry}
        material={nodes.Library24_StaticMeshComponent0.material}
        position={[-51.6, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library25_StaticMeshComponent0.geometry}
        material={nodes.Library25_StaticMeshComponent0.material}
        position={[43.7, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library26_StaticMeshComponent0.geometry}
        material={nodes.Library26_StaticMeshComponent0.material}
        position={[50.9, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library27_StaticMeshComponent0.geometry}
        material={nodes.Library27_StaticMeshComponent0.material}
        position={[29.2, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library28_StaticMeshComponent0.geometry}
        material={nodes.Library28_StaticMeshComponent0.material}
        position={[36.4, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library29_StaticMeshComponent0.geometry}
        material={nodes.Library29_StaticMeshComponent0.material}
        position={[14.5, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library30_StaticMeshComponent0.geometry}
        material={nodes.Library30_StaticMeshComponent0.material}
        position={[21.7, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library31_StaticMeshComponent0.geometry}
        material={nodes.Library31_StaticMeshComponent0.material}
        position={[0, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library32_StaticMeshComponent0.geometry}
        material={nodes.Library32_StaticMeshComponent0.material}
        position={[7.2, 0.2, -68]}
      />
      <mesh
        geometry={nodes.Library33_StaticMeshComponent0.geometry}
        material={nodes.Library33_StaticMeshComponent0.material}
        position={[-15.1, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library34_StaticMeshComponent0.geometry}
        material={nodes.Library34_StaticMeshComponent0.material}
        position={[-7.9, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library35_StaticMeshComponent0.geometry}
        material={nodes.Library35_StaticMeshComponent0.material}
        position={[-29.6, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library36_StaticMeshComponent0.geometry}
        material={nodes.Library36_StaticMeshComponent0.material}
        position={[-22.4, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library37_StaticMeshComponent0.geometry}
        material={nodes.Library37_StaticMeshComponent0.material}
        position={[-44.3, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library38_StaticMeshComponent0.geometry}
        material={nodes.Library38_StaticMeshComponent0.material}
        position={[-37.1, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library39_StaticMeshComponent0.geometry}
        material={nodes.Library39_StaticMeshComponent0.material}
        position={[-58.8, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library40_StaticMeshComponent0.geometry}
        material={nodes.Library40_StaticMeshComponent0.material}
        position={[-51.6, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library41_StaticMeshComponent0.geometry}
        material={nodes.Library41_StaticMeshComponent0.material}
        position={[43.7, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library42_StaticMeshComponent0.geometry}
        material={nodes.Library42_StaticMeshComponent0.material}
        position={[50.9, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library43_StaticMeshComponent0.geometry}
        material={nodes.Library43_StaticMeshComponent0.material}
        position={[29.2, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library44_StaticMeshComponent0.geometry}
        material={nodes.Library44_StaticMeshComponent0.material}
        position={[36.4, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library45_StaticMeshComponent0.geometry}
        material={nodes.Library45_StaticMeshComponent0.material}
        position={[14.5, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library46_StaticMeshComponent0.geometry}
        material={nodes.Library46_StaticMeshComponent0.material}
        position={[21.7, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library47_StaticMeshComponent0.geometry}
        material={nodes.Library47_StaticMeshComponent0.material}
        position={[0, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library48_StaticMeshComponent0.geometry}
        material={nodes.Library48_StaticMeshComponent0.material}
        position={[7.2, 0.2, 42.8]}
      />
      <mesh
        geometry={nodes.Library49_StaticMeshComponent0.geometry}
        material={nodes.Library49_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -24.1]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library50_StaticMeshComponent0.geometry}
        material={nodes.Library50_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -16.9]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library51_StaticMeshComponent0.geometry}
        material={nodes.Library51_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -38.6]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library52_StaticMeshComponent0.geometry}
        material={nodes.Library52_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -31.4]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library53_StaticMeshComponent0.geometry}
        material={nodes.Library53_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -53.3]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library54_StaticMeshComponent0.geometry}
        material={nodes.Library54_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -46.1]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library55_StaticMeshComponent0.geometry}
        material={nodes.Library55_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -67.8]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library56_StaticMeshComponent0.geometry}
        material={nodes.Library56_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -60.6]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library57_StaticMeshComponent0.geometry}
        material={nodes.Library57_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 34.7]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library58_StaticMeshComponent0.geometry}
        material={nodes.Library58_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 41.9]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library59_StaticMeshComponent0.geometry}
        material={nodes.Library59_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 20.2]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library60_StaticMeshComponent0.geometry}
        material={nodes.Library60_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 27.4]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library61_StaticMeshComponent0.geometry}
        material={nodes.Library61_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 5.5]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library62_StaticMeshComponent0.geometry}
        material={nodes.Library62_StaticMeshComponent0.material}
        position={[-61.3, 0.2, 12.7]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library63_StaticMeshComponent0.geometry}
        material={nodes.Library63_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -9]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Library64_StaticMeshComponent0.geometry}
        material={nodes.Library64_StaticMeshComponent0.material}
        position={[-61.3, 0.2, -1.8]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes['0_SM_FloatingIsland_S_5_StaticMeshComponent0'].geometry}
        material={materials.BasicAsset03}
        position={[5.5, -3.4, -9.6]}
      />
    </group>
  )
}

useGLTF.preload('/models/Sample_Map_Reference.glb')
