/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { extend, useFrame, useLoader } from "@react-three/fiber"
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef()
  const banner = useLoader(THREE.TextureLoader, '/Textures/TBuildingsBlueB.webp')
  const { nodes, materials } = useGLTF('/Models/Banners/SKBannerA.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.SK_Banner_A.geometry}
        castShadow transparent
        receiveShadow
        skeleton={nodes.SK_Banner_A.skeleton}>
        <meshStandardMaterial map={banner}></meshStandardMaterial>

      </mesh>
    </group>
  )
}

useGLTF.preload('/Models/Banners/SKBannerA.glb')
