/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({tree1=0x60200F,tree2=0xCF922E,rock= 0x8f8f8a,grass= 0x4FBD34,...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/TreeCut.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[3.23, 0.02, -4.77]} rotation={[Math.PI / 2, 0, 2.57]} scale={[0.47, 0.47, 0.47]}>
        <mesh geometry={nodes.Mesh007.geometry}>
          <meshStandardMaterial color={tree1}/>
        </mesh>
        <mesh geometry={nodes.Mesh007_1.geometry}>
          <meshStandardMaterial color={tree2}/>
        </mesh>
        <mesh geometry={nodes.Mesh007_2.geometry}>
          <meshStandardMaterial color={rock}/>
        </mesh>
        <mesh geometry={nodes.Mesh007_3.geometry}>
          <meshStandardMaterial color={grass}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/TreeCut.glb')
