/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/TreeBig-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.lowpoly_tree_04_Plane005.geometry}>
      <meshStandardMaterial color={0x1A3229}></meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.lowpoly_tree_04_Plane005_1.geometry}>
      <meshStandardMaterial color={0x3D200F}></meshStandardMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('models/TreeBig-transformed.glb')
