/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/tree2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 33.43, 0]} rotation={[Math.PI / 2, 0, -1.48]}>
        <mesh geometry={nodes.Cube266_leaves_0_1.geometry}>
        
        </mesh> 
        <mesh geometry={nodes.Cube266_leaves_0_2.geometry}>
        
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tree2.glb')
