/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({color1=0x836003, color2=0x35652B,...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Tree3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-5.21, 0.85, -0.84]} rotation={[Math.PI / 2, 0, 0]} scale={[0.35,0.35,0.35]}>
        <mesh geometry={nodes.lowpoly_tree_04_Plane067.geometry}>
        <meshStandardMaterial color={color1}></meshStandardMaterial>
        </mesh>
        <mesh geometry={nodes.lowpoly_tree_04_Plane067_1.geometry}>
        <meshStandardMaterial color={color2}></meshStandardMaterial>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Tree3.glb')
