/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { BuildingMat } from './Building.mat'

export default function Model({ ...props }) {
  const group = useRef()

  
  const { nodes, materials } = useGLTF('/models/Buildings/WallBwall.glb')
  return (
    <group  {...props} dispose={null}>
      <mesh ref={group} geometry={nodes.SM_Wall_B_wall.geometry}
      castShadow transparent
      receiveShadow >
      <BuildingMat></BuildingMat>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Buildings/WallBwall.glb')

