/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Well-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube004_Material004_0_1.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube004_Material004_0_2.geometry} material={nodes.Cube004_Material004_0_2.material} />
      <mesh geometry={nodes.rope_Material003_0.geometry} material={nodes.rope_Material003_0.material} />
      <mesh geometry={nodes.Cube008_Material005_0_1.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube008_Material005_0_2.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube008_Material005_0_3.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube008_Material005_0_4.geometry} material={nodes.Cube008_Material005_0_4.material} />
      <mesh geometry={nodes.Cube008_Material005_0_5.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Cube009_Wood_0.geometry} material={nodes.Cube009_Wood_0.material} />
      <mesh geometry={nodes.Cube018_Material006_0_1.geometry} material={nodes.Cube018_Material006_0_1.material} />
      <mesh geometry={nodes.Cube018_Material006_0_2.geometry} material={nodes.Cube018_Material006_0_2.material} />
      <mesh geometry={nodes.Cube062_Material006_0_1.geometry} material={nodes.Cube062_Material006_0_1.material} />
      <mesh geometry={nodes.Cube062_Material006_0_2.geometry} material={nodes.Cube062_Material006_0_2.material} />
      <mesh
        geometry={nodes.Icosphere010_Material003_0_1.geometry}
        material={nodes.Icosphere010_Material003_0_1.material}
      />
      <mesh geometry={nodes.Icosphere010_Material003_0_2.geometry} material={materials['Icosphere.003__0']} />
      <mesh
        geometry={nodes.Icosphere010_Material003_0_3.geometry}
        material={nodes.Icosphere010_Material003_0_3.material}
      />
    </group>
  )
}

useGLTF.preload('models/Well-transformed.glb')
